// flow-typed signature: b0f9b95ad3e390de61491ae4ee2e6971
// flow-typed version: <<STUB>>/file-loader_v^1.1.6/flow_v0.63.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "file-loader" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "file-loader/dist/cjs" {
  declare module.exports: any;
}

declare module "file-loader/dist/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "file-loader/dist/cjs.js" {
  declare module.exports: $Exports<"file-loader/dist/cjs">;
}
declare module "file-loader/dist/index.js" {
  declare module.exports: $Exports<"file-loader/dist/index">;
}
