// flow-typed signature: da9095dd17da16f63b575c07b4cadf1a
// flow-typed version: <<STUB>>/ijavascript_v^5.0.17/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ijavascript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ijavascript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ijavascript/bin/ijavascript' {
  declare module.exports: any;
}

declare module 'ijavascript/bin/ijsconsole' {
  declare module.exports: any;
}

declare module 'ijavascript/bin/ijsinstall' {
  declare module.exports: any;
}

declare module 'ijavascript/bin/ijsnotebook' {
  declare module.exports: any;
}

declare module 'ijavascript/bin/rc' {
  declare module.exports: any;
}

declare module 'ijavascript/lib/kernel' {
  declare module.exports: any;
}

declare module 'ijavascript/scripts/doc-publish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ijavascript/bin/ijavascript.js' {
  declare module.exports: $Exports<'ijavascript/bin/ijavascript'>;
}
declare module 'ijavascript/bin/ijsconsole.js' {
  declare module.exports: $Exports<'ijavascript/bin/ijsconsole'>;
}
declare module 'ijavascript/bin/ijsinstall.js' {
  declare module.exports: $Exports<'ijavascript/bin/ijsinstall'>;
}
declare module 'ijavascript/bin/ijsnotebook.js' {
  declare module.exports: $Exports<'ijavascript/bin/ijsnotebook'>;
}
declare module 'ijavascript/bin/rc.js' {
  declare module.exports: $Exports<'ijavascript/bin/rc'>;
}
declare module 'ijavascript/index' {
  declare module.exports: $Exports<'ijavascript'>;
}
declare module 'ijavascript/index.js' {
  declare module.exports: $Exports<'ijavascript'>;
}
declare module 'ijavascript/lib/kernel.js' {
  declare module.exports: $Exports<'ijavascript/lib/kernel'>;
}
declare module 'ijavascript/scripts/doc-publish.js' {
  declare module.exports: $Exports<'ijavascript/scripts/doc-publish'>;
}
