// flow-typed signature: c79d7e6e3792044860f1a81822c31891
// flow-typed version: <<STUB>>/nteract-assets_v^3.0.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nteract-assets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nteract-assets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'nteract-assets/index' {
  declare module.exports: $Exports<'nteract-assets'>;
}
declare module 'nteract-assets/index.js' {
  declare module.exports: $Exports<'nteract-assets'>;
}
