// flow-typed signature: 68f2023b5d34f0f6babca6978d0b2006
// flow-typed version: <<STUB>>/spawn-rx_v^2.0.11/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spawn-rx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spawn-rx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spawn-rx/lib/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spawn-rx/lib/src/index.js' {
  declare module.exports: $Exports<'spawn-rx/lib/src/index'>;
}
