// flow-typed signature: ac2629e5580871c53b2e2ce38c0ba9b5
// flow-typed version: <<STUB>>/vega-embed_v3.7.0/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vega-embed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "vega-embed" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "vega-embed/build/embed" {
  declare module.exports: any;
}

declare module "vega-embed/build/index" {
  declare module.exports: any;
}

declare module "vega-embed/build/post" {
  declare module.exports: any;
}

declare module "vega-embed/build/vega-embed" {
  declare module.exports: any;
}

declare module "vega-embed/build/vega-embed.min" {
  declare module.exports: any;
}

declare module "vega-embed/rollup.config" {
  declare module.exports: any;
}

// Filename aliases
declare module "vega-embed/build/embed.js" {
  declare module.exports: $Exports<"vega-embed/build/embed">;
}
declare module "vega-embed/build/index.js" {
  declare module.exports: $Exports<"vega-embed/build/index">;
}
declare module "vega-embed/build/post.js" {
  declare module.exports: $Exports<"vega-embed/build/post">;
}
declare module "vega-embed/build/vega-embed.js" {
  declare module.exports: $Exports<"vega-embed/build/vega-embed">;
}
declare module "vega-embed/build/vega-embed.min.js" {
  declare module.exports: $Exports<"vega-embed/build/vega-embed.min">;
}
declare module "vega-embed/rollup.config.js" {
  declare module.exports: $Exports<"vega-embed/rollup.config">;
}
