// flow-typed signature: 3b5c2e11b1e074acbf3a254168742a22
// flow-typed version: <<STUB>>/@nteract/plotly_v^1.0.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nteract/plotly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nteract/plotly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nteract/plotly/plotly.min' {
  declare module.exports: any;
}

declare module '@nteract/plotly/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nteract/plotly/plotly.min.js' {
  declare module.exports: $Exports<'@nteract/plotly/plotly.min'>;
}
declare module '@nteract/plotly/test.js' {
  declare module.exports: $Exports<'@nteract/plotly/test'>;
}
